<script setup lang="ts">
import { computed, ref } from 'vue'

const props = defineProps<{
    narrative: string
    providerUsed?: string
    isLoading?: boolean
    reportTitle?: string
}>()

const copied = ref(false)

// Format narrative with proper line breaks
const formattedNarrative = computed(() => {
    if (!props.narrative) return ''

    return props.narrative
        .split('\n')
        .filter((line) => line.trim() !== '')
        .join('\n\n')
})

const hasNarrative = computed(() => {
    return props.narrative && props.narrative.trim() !== ''
})

// Provider badge color based on provider name
const providerBadgeColor = computed(() => {
    if (!props.providerUsed) return 'bg-gray-100 text-gray-600'

    const provider = props.providerUsed.toLowerCase()
    if (provider.includes('gemini')) return 'bg-blue-50 text-blue-700'
    if (provider.includes('kimi')) return 'bg-violet-50 text-violet-700'
    if (provider.includes('glm')) return 'bg-orange-50 text-orange-700'
    if (provider.includes('nvidia')) return 'bg-green-50 text-green-700'
    if (provider.includes('minimax')) return 'bg-pink-50 text-pink-700'
    if (provider.includes('claude')) return 'bg-amber-50 text-amber-700'

    return 'bg-gray-100 text-gray-600'
})

const copyNarrative = async () => {
    if (!props.narrative) return
    try {
        await navigator.clipboard.writeText(props.narrative)
        copied.value = true
        setTimeout(() => { copied.value = false }, 2000)
    } catch {
        // Fallback
        const textarea = document.createElement('textarea')
        textarea.value = props.narrative
        document.body.appendChild(textarea)
        textarea.select()
        document.execCommand('copy')
        document.body.removeChild(textarea)
        copied.value = true
        setTimeout(() => { copied.value = false }, 2000)
    }
}

const printNarrative = () => {
    const printWindow = window.open('', '_blank')
    if (!printWindow) return

    printWindow.document.write(`
        <!DOCTYPE html>
        <html>
        <head>
            <title>Narasi Analisis — DataNarasi</title>
            <style>
                body { font-family: 'Segoe UI', system-ui, sans-serif; max-width: 700px; margin: 40px auto; padding: 0 24px; color: #1e293b; line-height: 1.7; }
                h1 { font-size: 18px; color: #0d9488; margin-bottom: 4px; }
                .meta { font-size: 12px; color: #94a3b8; margin-bottom: 24px; }
                .content { font-size: 14px; white-space: pre-line; }
                hr { border: none; border-top: 1px solid #e2e8f0; margin: 24px 0; }
                .footer { font-size: 11px; color: #cbd5e1; text-align: center; }
            </style>
        </head>
        <body>
            <h1>Narasi Analisis</h1>
            <div class="meta">AI Provider: ${props.providerUsed || '-'} · ${new Date().toLocaleDateString('id-ID')}</div>
            <div class="content">${formattedNarrative.value}</div>
            <hr>
            <div class="footer">Generated by DataNarasi</div>
        </body>
        </html>
    `)
    printWindow.document.close()
    printWindow.print()
}

const downloadTxt = () => {
    if (!props.narrative) return
    const title = props.reportTitle || 'DataNarasi Report'
    const content = [
        `=== ${title} ===`,
        `Tanggal: ${new Date().toLocaleDateString('id-ID', { day: 'numeric', month: 'long', year: 'numeric' })}`,
        `AI Provider: ${props.providerUsed || '-'}`,
        '',
        '--- NARASI ANALISIS ---',
        '',
        props.narrative,
        '',
        '---',
        'Generated by DataNarasi'
    ].join('\n')

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${title.replace(/[^a-zA-Z0-9]/g, '_')}_narasi.txt`
    a.click()
    URL.revokeObjectURL(url)
}

// Word count
const wordCount = computed(() => {
    if (!props.narrative) return 0
    return props.narrative.trim().split(/\s+/).length
})
</script>

<template>
    <div class="rounded-xl border border-gray-200 bg-white overflow-hidden">
        <!-- Header -->
        <div class="px-5 py-3.5 border-b border-gray-100 flex items-center justify-between">
            <div class="flex items-center gap-3">
                <h3 class="text-sm font-semibold text-gray-700">Narasi Analisis</h3>
                <span
                    v-if="providerUsed"
                    class="text-[10px] px-2 py-0.5 rounded-full font-medium"
                    :class="providerBadgeColor"
                >
                    {{ providerUsed }}
                </span>
            </div>

            <!-- Actions -->
            <div v-if="hasNarrative" class="flex items-center gap-1.5">
                <span class="text-[11px] text-gray-400 mr-2">{{ wordCount }} kata</span>
                <button
                    @click="copyNarrative"
                    class="inline-flex items-center gap-1 text-xs text-gray-500 hover:text-gray-700 px-2 py-1.5 rounded-md hover:bg-gray-50 transition-colors"
                    :title="copied ? 'Tersalin!' : 'Salin teks'"
                >
                    <svg v-if="!copied" class="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
                    </svg>
                    <svg v-else class="w-3.5 h-3.5 text-emerald-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
                    </svg>
                    <span>{{ copied ? 'Tersalin' : 'Salin' }}</span>
                </button>
                <button
                    @click="printNarrative"
                    class="inline-flex items-center gap-1 text-xs text-gray-500 hover:text-gray-700 px-2 py-1.5 rounded-md hover:bg-gray-50 transition-colors"
                    title="Cetak narasi"
                >
                    <svg class="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" />
                    </svg>
                    <span>Cetak</span>
                </button>
                <button
                    @click="downloadTxt"
                    class="inline-flex items-center gap-1 text-xs text-gray-500 hover:text-gray-700 px-2 py-1.5 rounded-md hover:bg-gray-50 transition-colors"
                    title="Download sebagai .txt"
                >
                    <svg class="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                    </svg>
                    <span>Download</span>
                </button>
            </div>
        </div>

        <!-- Loading State -->
        <div v-if="isLoading" class="p-6">
            <div class="space-y-3 animate-pulse">
                <div class="h-3.5 bg-gray-100 rounded w-3/4"></div>
                <div class="h-3.5 bg-gray-100 rounded w-full"></div>
                <div class="h-3.5 bg-gray-100 rounded w-5/6"></div>
                <div class="h-3.5 bg-gray-100 rounded w-2/3"></div>
            </div>
        </div>

        <!-- Narrative Content -->
        <div v-else-if="hasNarrative" class="px-5 py-5">
            <div class="text-sm text-gray-700 leading-[1.8] whitespace-pre-line">
                {{ formattedNarrative }}
            </div>
        </div>

        <!-- Empty State -->
        <div v-else class="px-5 py-12 text-center">
            <div class="text-gray-300 text-3xl mb-3">📝</div>
            <h3 class="text-sm font-medium text-gray-500 mb-1">Belum Ada Narasi</h3>
            <p class="text-xs text-gray-400">
                Narasi akan muncul setelah processing selesai.
            </p>
        </div>
    </div>
</template>
